### ISSUE TITLE
aurelia-hide style does not penetrate shadow DOM

### ISSUE THREAD

**Issue by mattduffield** [aurelia/metadata#11]
I have noticed an issue with @useShadowDOM and the latest release.  It appears that shadow DOM is not working properly.

Please take a look at the following sample repository:

https://github.com/mattduffield/skeleton-navigation

I have created a TabControl and TabItem.  I am preserving the folder structure of my larger application and just included these two controls for this issues.  It turns out that if you use the @useShadowDOM in the TabItem js file, it no longer works.  I believe that @PWKad has determined that this might be something with regard to the latest bootstrap version as my controls use Bootstrap.

I am more than happy to do it the correct way if there is something that I am doing wrong.  I grabbed this code originally from @EisenbergEffect in one of the many posts he did on gitter.

**Comment by PWKad** [comment]
Actually I think this is due to `show`'s behavior in the shadow DOM

**Comment by EisenbergEffect** [comment]
@PWKad Could this be that the style used by the show attribute is not penetrating the shadow dom barrier? @mattduffield What is the behavior you are seeing? Is it that all the tabs are visible? But everything else is working?

**Comment by mattduffield** [comment]
Yes, you are correct.  It is how Rob is describing.  When I updated to the
latest, I saw all the tabs visible.  Everything else seemed to work just
fine outside of the tabs.

**Comment by EisenbergEffect** [comment]
I wonder, if you were to move the style inside the custom element, if that would solve the issue. This presents a really interesting issue, if it is what I think it is.

**Comment by EisenbergEffect** [comment]
@mattduffield Can you check in a browser that doesn't support shadow dom and see if everything works correctly for you? For example, safari of FF.

**Comment by mattduffield** [comment]
Safari works just fine on the Mac.
FireFox also works fine on the Mac.

**Comment by mattduffield** [comment]
I tested this with the attribute commented out....did you want me to test
with it uncommented?

**Comment by mattduffield** [comment]
Okay,

I tested both Safari and FireFox using @useShadowDOM and both worked
perfectly but when I opened the same with Chrome, it didn't work.
When I had @useShadowDOM commented out, all three worked fine.

**Comment by EisenbergEffect** [comment]
So, the show attribute will apply a style to the element based on true/false values. I believe that style is not having an affect because it's not visible inside the shadow DOM. Try using an `if` binding instead of `show` and see if that works. That's not a fix for our bug, but might get your code working for now.

**Comment by mattduffield** [comment]
Switching to if.bind the tabs become selected but no content is visible
across all three browsers.

**Comment by EisenbergEffect** [comment]
Ah. Switch  your content selector on your tab control to select="*" and see
if that fixes that issue.

On Mon, May 4, 2015 at 10:58 PM, Matt Duffield <notifications@github.com>
wrote:

> Switching to if.bind the tabs become selected but no content is visible
> across all three browsers.
>
> On Mon, May 4, 2015 at 10:53 PM, Rob Eisenberg <notifications@github.com>
> wrote:
>
> > So, the show attribute will apply a style to the element based on
> > true/false values. I believe that style is not having an affect because
> > it's not visible inside the shadow DOM. Try using an if binding instead
> > of show and see if that works. That's not a fix for our bug, but might
> > get your code working for now.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/aurelia/metadata/issues/11#issuecomment-98917163>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/metadata/issues/11#issuecomment-98918337>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by mattduffield** [comment]
Still using if.binding?

**Comment by mattduffield** [comment]
With if.bind, no change in Chrome.

**Comment by PWKad** [comment]
Ok I've just come back and tested this with show vs if and for me it is working as expected using `if`.

I think we can log this bug as the fact that `show`'s style does not penetrate the shadow DOM @EisenbergEffect

**Comment by PWKad** [comment]
@mattduffield Can you please change the name of this issue to `aurelia-hide style does not penetrate shadow DOM`

**Comment by mattduffield** [comment]
I have updated the name of this issue.  Thanks!

**Comment by EisenbergEffect** [comment]
This has been fixed.
