### ISSUE TITLE
System.normalize is not a function

### ISSUE THREAD

**Issue by benlaan** [aurelia/metadata#15]
After upgrading to bootstrapper 0.13.1 (and all its dependencies, including metadata 0.6.0), I am now unable to bootstrap my code.

I am using requirejs (AMD) as my loader, within a browser. I import aurelia-bootstrapper, which loads aurelia-framework, which loads aurelia-metadata. Once these dependencies are ready, boostrapper.run() calls ensureLoader(), which checks whether System exists, then tries to load via the System loader..

Which results in an error  "System.normalize is not a function". 

Obviously this is a problem, since window.System was an object created within metadata, NOT the loader

**Comment by EisenbergEffect** [comment]
Try updating to the latest version from (early) this morning. There's new versions of all libraries. I believe we have addressed this issue therein.

**Comment by benlaan** [comment]
This has done the trick.

Thanks
