### ISSUE TITLE
Meta data type problem with Typescript 1.6.0-beta

### ISSUE THREAD

**Issue by delebash** [aurelia/metadata#27]
Windows 7 x64
Typescript 1.6.0-beta or master branch same result
gulp-typescript 2.8.2

I am not sure if this is an aurelia issue or typescript.  Note this same code works fine  with Typescript 1.5.3

Here is the issue
Compiling this typescript 
import {bindable} from 'aurelia-framework';

export class SeHeader {
  @bindable router = null;

}

The js output line that is a problem is
   __metadata('design:type', Object)  this is what it is supposed to be and what ts 1.5 produces
However 1.6-beta produces
    __metadata('design:type', )  missing the Object

**Comment by EisenbergEffect** [comment]
It looks like a bug in the 1.6 compiler. Notice how the JavaScript it produces isn't even valid code. I would alert them to this asap.

**Comment by delebash** [comment]
ok

**Comment by delebash** [comment]
Well with a little searching it is already filed as a bug on typescript
https://github.com/Microsoft/TypeScript/issues/4549

**Comment by EisenbergEffect** [comment]
Great. Looks like they have someone working on it now.
