### ISSUE TITLE
parse decorators like @inject with mixin decorator

### ISSUE THREAD

**Issue by devmondo** [aurelia/metadata#28]
the new mixin decorator is great, i maybe wrong, but it does not take into account the applied decorators on the mixed sources.

an example of that is that we want to create a custom element and eliminate boiler plate code like we dont want to define arguments in the constructor nor inject deps every time we create one, below is an example

```
@inject(Element, Service)
export class Component {
    constructor(element, service) {
        this.element = element;
        this.service = service;
    }

    render() {
        console.log(`render method is called`);
    }
}

@mixin(Component)
export class ComposedElement {
    constructor() {
        console.log(this.element);
        console.log(this.service);
        this.render();
    }
}

```

in above both `this.element` and `this.service` are undefined because they are not taking into account during mixin.

**Comment by bebor** [comment]
does aurelia support a @mixin decorator at all?

**Comment by EisenbergEffect** [comment]
I would recommend that you create your own custom decorator to merge the specific things you care about into the object. Our mixin decorator was designed mostly for our own use and doesn't cover these types of scenarios.
