### ISSUE TITLE
Remove core-js runtime dependency

### ISSUE THREAD

**Issue by MrAndMrsK** [aurelia/metadata#29]
This would have to be tackled one repo at a time.  I started here.  I have a PR for this in the works.

See https://github.com/aurelia/framework/issues/294

**Comment by EisenbergEffect** [comment]
Ok, keep me posted. Also, the author of core-js contacted me and may have some ideas too. I bet we can do a combination of things to improve this. I'm interested to see what you put together. Thanks for taking on the challenge!

**Comment by MrAndMrsK** [comment]
Before I do a pull request or any CLA stuff, can you please review this commit (which I would submit as is, I think) and see if it's the way you want to go?  I don't assume I'd be doing the rest of them, but this would be a start - not sure how much bigger the other repos are and I'd like guidance on how to continue down the path if at all...

https://github.com/MrAndMrsK/metadata/commit/4b23faf2a111624f0accdc6cbbe8d7bbca39c929

Thanks

**Comment by EisenbergEffect** [comment]
Let's see if we can get a few other guys to look at this and see what direction we want to go. @jdanyow Take a look at this PR. Any thoughts on this or how we can remove the hard dependency on core-js. Should we remove it entirely and then feature detect and throw like this? It might work. We can still configure core-js by default in the skeles. @PWKad I would appreciate your feedback as well.

@MrAndMrsK There are some other apis we need to check as well. @ahmedshuhel Can you find that list of es6 apis that you created that we rely on?

**Comment by EisenbergEffect** [comment]
I wonder if we could add some asserting methods in pal that the various libraries could call to assert that what they need is present.

**Comment by MrAndMrsK** [comment]
Yes, it is true that the other aurelia modules also rely on other es6 features, but for this library these were the only two I noticed.  Each module, which I assume can be used possibly without their peers (in the aurelia-framework dependency tree) would have their own featureDetect script.  If this is missing a check, then it is because I missed its usage.

**Comment by jdanyow** [comment]
agree- lets add some assert methods to the PAL, memoizing as-needed.  Need to figure out how to write tests for these as well.

**Comment by EisenbergEffect** [comment]
All done :)
