### ISSUE TITLE
Latest aurelia-metadata library causes decorators to fail in aurelia-validation

### ISSUE THREAD

**Issue by meash-nrel** [aurelia/metadata#30]
aurelia-validation 0.6.2 unit tests are passing (once missing [dependent libs](https://github.com/aurelia/validation/issues/217) are installed) when using aurelia-metadata 1.1.3.

updating aurelia-metadata to 1.1.4 causes the library's **ensure** decorator to stop working altogether.  see https://github.com/aurelia/validation/issues/216

`$jspm install aurelia-metadata`
`... Installed aurelia-metadata as npm:aurelia-metadata@^1.0.0-beta.1.1.4 (1.0.0-beta.1.1.4)`
`... aurelia-metadata 1.0.0-beta.1.1.3 -> 1.0.0-beta.1.1.4`

Unit tests in aurelia-validation will now fail - as the ensure decorator no longer functions.

Not seeing any commits in this package of note from 1.1.3 to 1.1.4.  What could be causing this inter-dependency failure?

**Comment by meash-nrel** [comment]
Looking at this library's dependencies, it's only aurelia-pal and core-js. Prior to updating aurelia-metadata from 1.1.3, i had already upgraded to aurelia-pal@1.0.0-beta.1.1.1, and core-js 2.1.0 in aurelia-validation.  So the latest versions of the underlying dependency libs were being used prior to aurelia-metadata being updated.  Everything was working.    

Update aurelia-metadata, though, and then decorators stop working.

**Comment by doktordirk** [comment]
core-js@2.0.3 might be the problem. 
see (https://github.com/aurelia/validation/issues/216#issuecomment-184217460)

**Comment by meash-nrel** [comment]
it appears the issue is due to core-js change vs shim in use.   closing this as it seems issue is within validation lib.

**Comment by meash-nrel** [comment]
> Before the core-js bump the aurelia metadata had it's own polyfills for metadata reflection, with the core-js update these were replaced by the core-js versions.

Unsure if metadata lib needs to reflect the shim diff or not.
