### ISSUE TITLE
Reflect.getOwnMetadata is not a function

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/metadata#37]
Suddenly got the following exception; 

> D:\Code\aurelia-template-lint\node_modules\aurelia-metadata\dist\commonjs\aureli
> a-metadata.js:34
>     return Reflect.getOwnMetadata(metadataKey, target, targetKey);
>                    ^
> TypeError: Reflect.getOwnMetadata is not a function
>     at Object.getOwn (D:\Code\aurelia-template-lint\node_modules\aurelia-metadat
> a\dist\commonjs\aurelia-metadata.js:34:20)
>     at Object.get (D:\Code\aurelia-template-lint\node_modules\aurelia-metadata\d
> ist\commonjs\aurelia-metadata.js:27:27)
>     at Container.autoRegister (D:\Code\aurelia-template-lint\node_modules\aureli
> a-dependency-injection\dist\commonjs\aurelia-dependency-injection.js:465:53)
>     at Container.get (D:\Code\aurelia-template-lint\node_modules\aurelia-depende
> ncy-injection\dist\commonjs\aurelia-dependency-injection.js:519:21)
>     at SyntaxRule.ASTBuilder (D:\Code\aurelia-template-lint\dist\ast.js:10:41)
>     at SyntaxRule (D:\Code\aurelia-template-lint\dist\rules\syntax.js:10:9)
>     at new AureliaLinter (D:\Code\aurelia-template-lint\dist\aurelia-linter.js:3
> 5:13)
>     at Object.<anonymous> (D:\Code\aurelia-template-lint\example.js:11:14)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)

What is rather troubling is that this has happened out of the blue and still happens after locking evertyhing to 1.0.0-rc.1.0.0

**Comment by MeirionHughes** [comment]
Ignore... I must be doing something wrong with the DI to cause it.

**Comment by doktordirk** [comment]
more a question if the right polyfills. make sure you have that
