### ISSUE TITLE
protocol decorator should return the target

### ISSUE THREAD

**Issue by tkhyn** [aurelia/metadata#40]
Hello, I ran into this issue when using aurelia-validation's [``validationRenderer``](https://github.com/aurelia/validation/blob/master/src/validation-renderer.js) decorator.

**I'm submitting a bug report**

I would expect the decorator returned by the ``protocol`` function to return the passed ``target``.

**Library Version:**
1.0.0-rc.1.0.1
**Please tell us about your environment:**
Not relevant

**Current behavior:**
protocol decorator returns ``undefined``

**Expected/desired behavior:**
protocol decorator should return the target or the resolved target so that other decorators  can be used. My use case is to use the transient decorator. Put it before and ``undefined`` is passed, put it after and ``validationRenderer`` cannot find the ``render`` and ``unrender`` methods/

**Suggested solutions**

1/ A wisely located `return target;` [here](https://github.com/aurelia/metadata/blob/master/src/protocol.js#L77) would fix the issue.

2/ If, for some reason, the function returned by ``protocol`` should not return anything, then it can be fixed in ``protocol.create`` [here](https://github.com/aurelia/metadata/blob/master/src/protocol.js#L96), using:

```javascript
  let result = function(target) {
    let decorator = protocol(name, options);
    if (target) {
      decorator(target);
      return target;
    }
    return decorator;
  };
```

**Comment by tkhyn** [comment]
Hum this is embarrassing, I simply added missing braces to ``transient`` and the issues I had disappeared ...

So the proposed changes are probably not necessary. Sorry to have bothered you for nothing, I'm closing this ...

**Comment by EisenbergEffect** [comment]
No worries. Decorators are a bit odd with the parent/no parens deals.
