### ISSUE TITLE
Issue with Origin.get in relation to aurelia-cli and require.js

### ISSUE THREAD

**Issue by izderadicka** [aurelia/metadata#41]
**I'm submitting a bug report**
- **Library Version:**
  1.0.0

**Please tell us about your environment:**
- **Operating System:**
  Linux  Ubuntu 14.04
- **Node Version:**
  v.4.5.0
- **NPM Version:**
  3.10.7
  <!--
- **JSPM OR Webpack AND Version**
  Require.js - as used in aurelia-cli
  require.js 2.2 or 2.3.1 - same behaviour
- **Browser:**
  Chromium 51.0.2704.79 Ubuntu 14.04 (64-bit)  & Firefox 48
- **Language:**
  ESNext

**Current behavior:**

Got unresponsive alert in FF, in chromium operation takes quite some time.  It related to displaying of a list of composed items , e.g. viewmodel is bound in each list item compose.

I tracked it down to this code in origin.js (line 37 an on):

```
 if (origin === undefined) {
      PLATFORM.eachModule((key, value) => {
        for (let name in value) {
          let exp = value[name];
          if (exp === fn) {
            originStorage.set(fn, origin = new Origin(key, name));
            return true;
          }
}
```

What actually happens is that PLATFOM.eachModule is iterating over packed modules - even files from text plugin, which then are passed here as string value.  The for loop is then running for each letter in string - so for large css (like bootstrap)  - it takes quite a lot of time.

This code is actually reached from createController, in CompositionEngine -  it loads VMs for for composed items - and if there are about 100 items there is issue.

I think it can be replicated by this approach:
1) Create project with aurelia-cli
2) In aurelia.json add dependency to some big text file -  like bootstrap css:

```
{
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
              ]
          },
```

3) create page with repeat.for and compose to bind some ViewModels

**Expected/desired behavior:**
- **What is the expected behavior?**
  Not sure why I got on this code path, but it's I think it surely should not iterate over  text  files -  maybe problem is elsewhere - in code causing  PLATFORM.eachModule to include text files here.  But I expect JS to run smoothly -  in System.js packed version I did not have this issue.
- **What is the motivation / use case for changing the behavior?**
  I think this is bug which should be fixed.

**Comment by EisenbergEffect** [comment]
Yes, it's a difference in the two module loaders. I think a simple type check would fix it. @izderadicka Are you interested in contributing by submitting a PR to fix the issue?

**Comment by izderadicka** [comment]
I'll look into it over weekend.

On September 28, 2016 5:38:13 AM GMT+02:00, Rob Eisenberg <notifications@github.com> wrote:
>Yes, it's a difference in the two module loaders. I think a simple type
>check would fix it. @izderadicka Are you interested in contributing by
>submitting a PR to fix the issue?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/aurelia/metadata/issues/41#issuecomment-250063724

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by EisenbergEffect** [comment]
Fixed.
