### ISSUE TITLE
peerDeps on aurelia-polyfills?

### ISSUE THREAD

**Issue by unional** [aurelia/metadata#46]
Should `aurelia-metadata` list `aurelia-polyfills` as peerDeps? It is used [here](https://github.com/aurelia/metadata/blob/master/src/metadata.js#L69) and [here](https://github.com/aurelia/metadata/blob/master/src/metadata.js#L72)

**Comment by EisenbergEffect** [comment]
Nope. We're trying to keep the libraries free of polyfill dependencies since they won't be needed eventually.
