### ISSUE TITLE
Internet Explorer 11 - Object.getPrototypeOf('aurelia-dom-boundary') error

### ISSUE THREAD

**Issue by jdanyow** [aurelia/metadata#47]
![image](https://cloud.githubusercontent.com/assets/1306747/21233569/993f36ec-c2bd-11e6-8319-a663a9aef05d.png)

In IE11, Object.getPrototypeOf breaks when it's passed a string.

**Comment by jdanyow** [comment]
Previous stack frame:

![image](https://cloud.githubusercontent.com/assets/1306747/21233849/c8efa7c2-c2be-11e6-81ef-ae27627070c3.png)

**Comment by jdanyow** [comment]
https://github.com/aurelia/templating-resources/blob/master/src/show.js#L11

**Comment by jdanyow** [comment]
Adding core-js makes things fail sooner, here:

![image](https://cloud.githubusercontent.com/assets/1306747/21234885/80592502-c2c2-11e6-878d-e267fa98529c.png)

core-js does make it possible to do `Object.getPrototypeOf('a string')` in the console.

**Comment by jdanyow** [comment]
looks like there's already an issue open for this:

https://github.com/aurelia/templating-resources/issues/267

Keeping this open for now in case the details are helpful.

**Comment by MarkHerhold** [comment]
Just started hitting this error, I suspect one of my dependencies got updated and I didn't notice.

Thanks for reporting this issue @jdanyow

**Comment by pKrav75** [comment]
Hit this one too !

**Comment by CasiOo** [comment]
Is a fix coming out soon? This is a critical bug from what I can see and have experienced.
We are unable to have any `show` binding in our application because of this IE bug. And we're binding to a regular VM boolean property, so a common case..

**Comment by altenstedt** [comment]
@CasiOo As a workaround, we have reverted package aurelia-dependency-injection to version 1.2.0.

**Comment by EisenbergEffect** [comment]
Yes. It's coming soon. In the mean time, just revert your DI back one version.

**Comment by EisenbergEffect** [comment]
Fixed. Releasing in just a minute.

**Comment by rapitkan** [comment]
I got this error: Object.getPrototypeOf: 'this' is not an Object (in June 2017) but got it fixed by downgrading from 1.2.1 to 1.2.0.
