### ISSUE TITLE
Specify aurelia-pal version in typings dependency.

### ISSUE THREAD

**Issue by jp7677** [aurelia/metadata#49]
Hi there,

When installing the TypeScript typings for a project that uses aurelia-metadata with `typings install` you will see the following output:

```
typings WARN badlocation "github:aurelia/pal" is mutable and may change, consider specifying a commit hash
├─┬ aurelia-metadata
│ └── aurelia-pal
```
This happens because https://github.com/aurelia/metadata/blob/master/typings.json does not specifies a version. Wouldn't it be better if the aurelia-pal dependency was specified as e.g.
`"aurelia-pal": "github:aurelia/pal#1.0.0"`
instead of just
`"aurelia-pal": "github:aurelia/pal"`.
That would resolve the imho justified warning.

PS: The same applies to https://github.com/aurelia/pal-browser/blob/master/typings.json.

**Comment by loku02** [comment]
Any progress here? This doesn't change for almost a year now.

**Comment by jp7677** [comment]
I had moved from jspm/typings to webpack some time ago. Closing this since this is no longer an issue for me.
