### ISSUE TITLE
Reflect.getOwnMetadata fails on nodejs

### ISSUE THREAD

**Issue by weagle08** [aurelia/metadata#50]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.3.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
JSPM 0.16.32

* **Browser:**
Chrome

* **Language:**
Typescript 2.1.x

**Current behavior:**

Using the aurelia-dependency-injection with nodejs fails if aurelia-polyfills is not included. Could this be an import for aurelia-metadata?

**Expected/desired behavior:**

would like to not have to import 'aurelia-polyfills' every time I use Aurelia dependency injection in NodeJS.

* **What is the expected behavior?**

 import 'aurelia-polyfills' not needed

* **What is the motivation / use case for changing the behavior?**

To make work properly in NodeJS

**Comment by EisenbergEffect** [comment]
NodeJS needs the polyfill, so you have add it. We don't force an import because certain platforms may not need or may choose to use a different set of polyfills.

**Comment by weagle08** [comment]
Ok, thanks for reply... Yeah I do the import once in my start up file so not a huge issue, but just thought it was odd it would fail out of the box on Node and the user doesn't have a clear reason as to what needs to be done to fix it.
