### ISSUE TITLE
Typings are referencing aurelia-pal master typing

### ISSUE THREAD

**Issue by GabrielMancik** [aurelia/metadata#57]
We are using aurelia-metadata 1.3.0 for a while. Suddenly our project is not buildable because aurelia-pal typings have changed recently and are no longer compatible with Typescript 2.5 we are currently using. Upgrading typescript will probably fix this issue, but I think release packages should be "immutable".

**Comment by Alexander-Taran** [comment]
typings that come with packages do not change..
you are probably using typings from master branch

**Comment by GabrielMancik** [comment]
I am not. typings.json in version 1.3.0 have dependencies declared like this:
 
```
"dependencies": {
    "aurelia-pal": "github:aurelia/pal"
}
```

not declaring version of aurelia pal will result in download of master typing. Or?

**Comment by bigopon** [comment]
May I know which part is failing in your project, error message would be nice ? I don't recall using any very new feature of TypeScript in `aurelia-pal`, 2.5 even 2.3 should work

**Comment by GabrielMancik** [comment]
We have errors directly in typings on the line:
createCustomEvent<T = any>(eventType: string, options?: CustomEventInit<T>): CustomEvent<T>;
and the error is that CustomEventInit is not generic type .. It was not in typescript 2.5 but is in latest

**Comment by bigopon** [comment]
@GabrielMancik would be nice if you could PR to fix it 😸
