### ISSUE TITLE
Incorrect view-model metadata while unit-testing

### ISSUE THREAD

**Issue by Sayan751** [aurelia/metadata#59]
**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.10.0

* **NPM Version:**
6.0.1

* **JSPM OR Webpack AND Version**
webpack ^4.8.3

* **Browser:**
all

* **Language:**
TypeScript 2.8.3

**Current behavior:**
Though I am not completely sure if this issue belongs here, at this point it seems that this is most relevant repository for this issue. 

I am trying to unit test my simple custom elements, namely `NormalText` and `ValueText`, both of which inherits from `BaseText`. This is shown below.
```TypeScript
// BaseText.ts
import { bindable } from "aurelia-framework";
import { BaseI18N } from "aurelia-i18n";

export class BaseText extends BaseI18N {
    @bindable public value: string;
    @bindable public i18nKey: string;
}

// NormalText.ts
export class NormalTextCustomElement extends BaseText { }

// ValueText.ts
export class ValueTextCustomElement extends BaseText { }
```
```html
<!-- NormalText.html -->
<template>
    <span t.bind="i18nKey">${value}</span>
</template>

<!-- ValueText.html -->
<template>
    <strong t.bind="i18nKey">${value}</strong>
</template>
```

While trying to unit-test (Jasmine + Karma + Webpack) the views of these two custom elements, I ran into a problem, where metadata of the ViewModel class, whose test suite is running second had incorrect metadata. This is the reason why my second test suite is also failing.

For example, if the test suite for `NormalText` is ran first, then for the test suite of `ValueText`, metadata of `ValueText` reflected metadata of `NormalText` (the HTML/view resources of `NormalText`). More specifically, in this particular running example, there is no metadata directly in `ValueText`; and that's why [the `prototype` of `ValueText`, in this case `BaseText`, is checked for metadata](https://github.com/aurelia/metadata/blob/master/src/metadata.js#L71). When metadata of `BaseText` is checked, it returned information about the view of `NormalText`!!

A workaround can be to use `@customElement` decorator on both of these classes. I also asked about this  problem in this [SO question](https://stackoverflow.com/questions/50639875/underterministic-unit-test-issues-with-aurelia-testing) and [reported](https://stackoverflow.com/a/50715488/2270340) the workaround.

**Expected/desired behavior:**

To reproduce the bug, one can check my [GitHub repo](https://github.com/Sayan751/test-au-plugin). If you do so, then don't forget to remove the decorators.

* **What is the expected behavior?**
As the name of custom elements stick to the conventions, it is expected that those custom elements should work without any decorators.

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
@Sayan751 Thanks for reporting this issue. I'm sorry that no one responded earlier. It must have gone under the radar somehow. Inheritance has always been a challenge with custom elements, due to these types of issues with metadata. There have been some improvements within the last year but there are some important requirements in how it is used. In particular, the presence of the decorator is required in this scenario in order to properly allow/disallow various data to flow correctly. You can find more information in the documentation here: https://aurelia.io/docs/templating/html-behaviors#inheritance-with-html-behaviors

**Comment by bigopon** [comment]
@EisenbergEffect i have a fix in mind to deal with this, but im not sure how we should look at such change, in terms of versioning

**Comment by bigopon** [comment]
Its a simple fix. We add a property on module analyzer to switch the behavior of walking up the proto chain. If there is already a workaround, so probably we let it work this way then.

**Comment by bigopon** [comment]
I meant if we want to avoid breaking change, its an extra flag and change few lines of code. Or if we can work out if its not a breaking change, we can fiz it directly

**Comment by EisenbergEffect** [comment]
I don't think we should mess with metadata and start adding flags at this point since we've got a solution that's documented.

**Comment by EisenbergEffect** [comment]
Following up here for @Sayan751 We're still debating this a bit but the change would not be in this module, rather in how templating uses this module. We're exploring there a bit.

**Comment by Sayan751** [comment]
> 
> 
> @Sayan751 Thanks for reporting this issue. I'm sorry that no one responded earlier. It must have gone under the radar somehow. Inheritance has always been a challenge with custom elements, due to these types of issues with metadata. There have been some improvements within the last year but there are some important requirements in how it is used. In particular, the presence of the decorator is required in this scenario in order to properly allow/disallow various data to flow correctly. You can find more information in the documentation here: https://aurelia.io/docs/templating/html-behaviors#inheritance-with-html-behaviors

Thank you for the link to documentation. Somehow I missed that earlier. Maybe it is better to update the relevant part of the documentation with a bit more details on the reason for applying the `@customElement` decorator.
