### ISSUE TITLE
Dist/Types folder directory is missing on master.

### ISSUE THREAD

**Issue by LukeTPerry** [aurelia/metadata#70]
https://github.com/aurelia/metadata/blob/1213cdb263177d9ff8d734e6db5cc9536f09893b/typings.json#L3

Hello,

Apologises for not following the template. It seemed a bit extreme for what the issue ultimately is.

"dist/types/aurelia-metadata.d.ts"

"dist/types/" directory is currently not on master and as such builds referencing the master branch are failing when they can not retrieve typings.json.

![image](https://user-images.githubusercontent.com/10466424/110333184-32d09400-8019-11eb-98e7-f72a0a7f6e80.png)
![image](https://user-images.githubusercontent.com/10466424/110333179-2fd5a380-8019-11eb-9928-1845be37f539.png)

As a workaround and to assist anyone else with the same issue, we are now explicitly targeting 1.0.7 in our typings.json

`"aurelia-metadata": "github:aurelia/metadata#1.0.7",`

Thanks

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @LukeTPerry ?

**Comment by bigopon** [comment]
1.0.8 has been published. Thanks @LukeTPerry
