### ISSUE TITLE
Remove AtScript support in favor of Typescript 1.5

### ISSUE THREAD

**Issue by delebash** [aurelia/metadata#8]
Since Angular 2.0 is dropping the development of AtScript and merging it with TypeScript 1.5, I would think that Aurelia will also drop AtScript?

**Comment by EisenbergEffect** [comment]
Yes. Probably next week we'll be updating our metadata implementation to take advantage of ES7 Decorators and will retire anything AtScript specific shortly thereafter.

**Comment by matjaz** [comment]
Is there any transpiler supporting decorators?
It would be a shame to drop support for annotations before we could use decorators.

**Comment by delebash** [comment]
It's not clear to me if/when typescript will have decorators, it is certainly being discussed and I thought as they moved to 1.5 all of the atscript features where going to be merged.

I was under the impression that typescript 1.5 will have annotations but I guess there is a difference between annotations and decorators, which I am still trying to wrap my head around

Here is part of the discussion on typescript decorators vs annotations, and links to other similar issues.  
https://github.com/Microsoft/TypeScript/issues/1557

**Comment by EisenbergEffect** [comment]
So, what we'll do is add the decorator implementations to Aurelia, probably next week. This is based on the current ES7 spec. We won't remove the AtScript support until after there is actually support in TypeScript for Decorators.

I'm hopeful that Babel will also implement ES7 Decorators soon. That's probably dependent on Yehuda Katz finishing up the proposal spec....which is slightly different than TypeScript's since they have some extra bits related to types which aren't part of the ES7 proposal.

**Comment by dbones** [comment]
+1 for this topic (very interested in Typescript)

If it helps, @EisenbergEffect - I had a (quick) look around the TS 1.5, borrowing from the demo Angular 2.0/Typescript code and applied the following to work with aurelia DI. [here - annotations for DI](https://github.com/dbones/aurelia-ts/blob/master/src/annotations.ts)

I'm looking forward to see what you will implement.

**Comment by darcnite3000** [comment]
Babel has just implemented the proposal from Yehuda for decorators in babel 5, this is also in babelify 6.0.1 (requires options: ['es7.decorators'] in the config for them to work)

**Comment by EisenbergEffect** [comment]
Yes. We will have decorators in our next release for both Babel and TypeScript. It's coming probably on Wednesday.

**Comment by EisenbergEffect** [comment]
Releasing now with removal of AtScript. New release supports Babel 5.x and TypeScript 1.5.
